### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by patrick-nanys** [attilanagy234/syntax-augmentation-nmt#69]
After setting up the CI tooling it is visible that there are some tests that are failing.
- Find out why the tests are failing and fix them
- Completed when there is a PR with the tests passing

**Comment by attilanagy234** [comment]
Some of the tests are failing, because of the POS tag filtering logic that was merged to the main branch recently. Those should be fixed, once this is merged: https://github.com/attilanagy234/syntax-augmentation-nmt/pull/65

**Comment by patrick-nanys** [comment]
Just waiting for a review
